# Generated by Django 2.2 on 2019-06-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
